main/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('user.urls' , namespace='user')) , 
    path('manager/' , include('manager.urls' , namespace='manager'))
]

manager/urls.py
from django.urls import path
from . import views
from user import views as v



app_name = 'manager'

urlpatterns = [
    path('' , views.ManagerView.as_view() , name='manager') , 
    path('user_accounts/' , v.UserAccountsView.as_view() , name = 'acc')
]

manager/models.py
from django.db import models
from django.contrib.auth.models import User




# Create your models here.
class Gift(models.Model) : 
    code = models.CharField(max_length=100)
    day = models.IntegerField(default=0)
    count = models.IntegerField(default=0)
    used = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.code} - count {self.count} - used {self.used} - day {self.day}'



class Server(models.Model) : 
    link = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.link
    

class RunModel(models.Model) : 
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    server = models.ForeignKey(Server , on_delete=models.CASCADE)
    account = models.CharField(max_length=200)
    second = models.IntegerField()
    pid = models.IntegerField(default=0)
    second = models.IntegerField(default=0)

manager/views.py
from django.shortcuts import render , redirect
# Create your views here.
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models
import requests




class ManagerView(LoginRequiredMixin ,View) : 
    def dispatch(self, request, *args, **kwargs)  :
    
        if request.user.is_authenticated : 
            if request.user.is_superuser == False : 
                messages.success(request  , 'شما کاربر ادمین نیستی :(' , 'warning')
                return redirect('user:profile')
        return super().dispatch(request, *args, **kwargs)
    




    def get(self, request ) : 
        active = []
        servers = models.Server.objects.all()
        for i in servers : 
            try :
                res= requests.get(i.link)
                if res.status_code == 200 :
                    active.append(i) 
                else : 
                    models.Server.objects.get(id = i.id ).delete()
            except : 
                    models.Server.objects.get(id = i.id ).delete()



        return render(request , 'manager/admin.html' , {'servers' : active})
    

manager/templates/manager/admin.html
{% extends 'base.html' %}



{% block title %}
Admin
{% endblock %}



{% block main %}



<!-- On rows -->
<!-- On rows -->

<table class="table text-center">
    <caption>List of users</caption>
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">STATUS</th>
        <th scope="col">LINK</th>
      </tr>
    </thead>

    {% for i in servers %}
    

<tbody>
    <tr class="table-success">
      <th scope="row">{{i.id}}</th>
      <td>ONLINE</td>
      <td><a href="{{i.link}}">{{i.link}}</a></td>
    </tr>
  </tbody>
{% endfor %}


<br>

<div class="text-center">

    <a href="{% url 'manager:manager' %}" class="btn btn-info btn-lg text-center">
        <span class="glyphicon glyphicon-refresh"></span> تازه سازی
      </a>
</div>
<br><hr>





{% endblock%}