main/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('user.urls' , namespace='user')) , 
    path('manager/' , include('manager.urls' , namespace='manager'))
]

manager/urls.py
from django.urls import path
from . import views
from user import views as v



app_name = 'manager'

urlpatterns = [
    path('' , views.ManagerView.as_view() , name='manager') , 
    path('user_accounts/' , v.UserAccountsView.as_view() , name = 'acc')
]

user/urls.py
from django.urls import path
from . import views


app_name = 'user'

urlpatterns = [
    path('register/' , views.UserRegister.as_view() , name='register') , 
    path('login/' , views.UserLogin.as_view() , name='login') , 
    path('logout/' , views.UserLogOut.as_view() , name = 'logout') , 
    path('' , views.UserProfile.as_view() , name='profile') , 
    path('kill/<str:fpass>' , views.KillFpass.as_view() , name='kill')
]

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class UserRegisterForm(forms.Form) : 
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class' : 'form-control' ,
                                                                                   'placeholder' : 'یوزرنیم را وارد کنید'  , 
                                                                                   'class' : 'col-xs-2' , 
                                                                                   'class' : 'text-center'

                                                                                   }) , label='')
    email = forms.CharField(max_length=100, widget=forms.EmailInput(attrs={'class' : 'form-control' ,
                                                                                   'placeholder' : 'ایمیل را وارد کنید'  , 
                                                                                   'class' : 'col-xs-2' , 
                                                                                   'class' : 'text-center'

                                                                                   }) , label='')
    

    password = forms.CharField(max_length=100  , widget=forms.PasswordInput(attrs={'class' : 'form-control' ,
                                                                                   'placeholder' : 'پسورد را وارد کنید'  , 
                                                                                   'class' : 'col-xs-2' , 
                                                                                   'class' : 'text-center' ,

                                                                                   }) , label='')
    password2 = forms.CharField(max_length=100 , widget=forms.PasswordInput(attrs={'class' : 'form-control' ,
                                                                                   'placeholder' : 'تکرار پسورد را وارد کنید'  , 
                                                                                   'class' : 'col-xs-2' , 
                                                                                   'class' : 'text-center'

                                                                                   }) , label='')




    def clean_username(self ) : 
        username = self.cleaned_data['username']
        check = User.objects.filter(username=username).exists()
        if check : 
            raise ValidationError('این یوزر نیم وجود دارد .')
        return username


    def clean_email(self) : 
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('این ایمیل وجود دارد لطفا ایمیل دیگری استفاده کنید .')
        return email

    def clean(self) : 
        cd = super().clean()
        p1 = cd['password']
        p2 = cd['password2']


        if p1 and p2 and p1 != p2 : 
            raise ValidationError('پسورد ها با هم برابر نیستن .لطفا دوباره تلاش کنید .')
        

class UserLoginForm(forms.Form) : 
    username = forms.CharField(max_length=100  , widget=forms.TextInput(attrs={'class' : 'form-control' ,
                                                                                   'placeholder' : 'یوزرنیم را وارد کنید'  , 
                                                                                   'class' : 'col-xs-2' , 
                                                                                   'class' : 'text-center'

                                                                                   }) , label='')
    password = forms.CharField(max_length=100 , widget=forms.PasswordInput(attrs={'class' : 'form-control' ,
                                                                                   'placeholder' : 'پسورد را وارد کنید'  , 
                                                                                   'class' : 'col-xs-2' , 
                                                                                   'class' : 'text-center'

                                                                                   }) , label='')
    


class get_gift(forms.Form) : 
    code = forms.CharField(max_length=200 , 
                            widget=forms.TextInput(attrs={'class' : 'form-control' ,
                                                                             'placeholder' : 'کد هدیه را وارد کنید ' , 
                                                                             'class' : 'col-xs-2' , 
                                                                             'class' : 'text-center'}) , label='')


class add_fpass(forms.Form) : 
    fpass = forms.CharField(max_length=200  , widget=forms.TextInput(attrs={'class' : 'form-control' ,
                                                                             'placeholder' : 'فروت پس را وارد کنید' , 
                                                                             'class' : 'col-xs-2' , 
                                                                             'class' : 'text-center'}) , label='')
    

    second = forms.IntegerField(widget=forms.TextInput(attrs={'class' : 'form-control' ,
                                                                             'placeholder' : 'ثانیه را وارد کنید' , 
                                                                             'class' : 'col-xs-1' , 
                                                                             'class' : 'text-center' , 
                                                                             'type' : 'number' , 
                                                                             }) , label='')




# username = forms.CharField(widget=forms.TextInput(
#         attrs={
#         'class':'form-control',
#         'placeholder':'Username'
#         }
#     ))

user/views.py
from django.shortcuts import render , redirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import login , logout , authenticate
from . import forms
from django.contrib import messages
from . import models
import requests
from manager import models as md
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime
import json





class UserRegister(View) : 
    form_class = forms.UserRegisterForm

    def dispatch(self, request, *args, **kwargs)  :
        if request.user.is_authenticated : 
            messages.success(request  , 'ابتدا از حساب خارج شوید سپس دوباره امتحان کنید .' , 'warning')
            return redirect('user:login')
        return super().dispatch(request, *args, **kwargs)

    def get(self , request) : 

        form = self.form_class
        return render(request , 'user/register.html' , {'form' : form})
         
    def post(self , request) : 
        form = self.form_class(request.POST)
        if form.is_valid() : 
            cd = form.cleaned_data
            User.objects.create_user(cd['username'] , cd['email'] , cd['password'])
            messages.success(request , 'اکانت با موفقیت ایجاد شد . :)' , 'success')
            return redirect('user:profile')
            
        return render(request , 'user/register.html' , {'form' : form})



class UserLogin(View) : 

    form_class = forms.UserLoginForm
    def dispatch(self, request, *args, **kwargs)  :
        if request.user.is_authenticated : 
            messages.success(request  , 'ابتدا از اکانت خارج شوید.سپس وارد شوید .' , 'warning')
            return redirect('user:profile')
        return super().dispatch(request, *args, **kwargs)
    def get(self , request) :
        form = self.form_class 
        return render(request , 'user/login.html' , {'form' : form})
        
    def post(self , request) : 
        form = self.form_class(request.POST)
        if form.is_valid() : 
            cd = form.cleaned_data
            check = authenticate(request , username=cd['username'] , password =cd['password'] )
            if check is not None : 
                login(request , check)
                messages.success(request , 'با موفقیت وارد حساب کاربری شدید .' , 'success')
                return redirect('user:profile')
            messages.success(request  , 'خطا دوباره امتحان کنید .' , 'warning')
            return redirect('user:login')
        



class UserLogOut(LoginRequiredMixin ,View) : 
    def get(self , request) : 
        logout(request)
        messages.success(request  , 'با موفقیت از اکانت خارج شدید.' , 'success')
        return redirect('user:profile')
    



class UserProfile(LoginRequiredMixin , View) : 
    def dispatch(self, request, *args, **kwargs)  :
            if request.user.is_superuser: 
                messages.success(request  , 'پنل مدیریت ادمین خوش اومدی :)' , 'success')
                return redirect('manager:manager')
            return super().dispatch(request, *args, **kwargs)
    


    def get(self , request) :
        
        form = forms.get_gift()
        account_form = forms.add_fpass()
        user = User.objects.get(id = request.user.id)
        days = user.userdata.subscription-datetime.datetime.now().date()
        day = days.days

        if days.days >1 : 
            sub = True
        else :
            sub = False
            user.userdata.account_count = 0
            user.userdata.account_used = 0
            user.userdata.save()
            accounts = models.UserAccounts.objects.filter(user = request.user.id)
            if accounts.exists() : 
                accounts.delete()


            
        useracc = models.UserAccounts.objects.filter(user = request.user.id)
        if useracc.exists() : 
            for i in useracc : 
                NameOP= {'User-Agent' : "Dalvik/2.1.0 (Linux; U; Android 13; SM-A326B Build/TP1A.220624.014)" ,'Connection':'close','Content-Type':"application/x-www-form-urlencoded" ,'Cookie':"FRUITPASSPORT="f"{i.fpass}"}
                data = requests.get('http://iran.fruitcraft.ir/cards/collectgold' , headers = NameOP)
                content = data.content
                if data.status_code == 200 and  len(content) < 500: 
                    x = json.loads(data.content)
                    redata = x['data']
                    acc = models.UserAccounts.objects.get(id = i.id)
                    acc.collected_gold = str(redata.get('collected_gold')) , 
                    acc.player_gold = str(redata.get('player_gold')) , 
                    acc.gold_collection_allowed = str(redata.get('gold_collection_allowed')), 
                    acc.gold_collection_allowed_at = str(redata.get('gold_collection_allowed_at')) , 
                    acc.gold_collection_extraction = str(redata.get('gold_collection_extraction')) , 
                    acc.last_gold_collect_at = str(redata.get('last_gold_collect_at')) , 
                    acc.needs_captcha = str(redata.get('needs_captcha')) , 
                    acc.save()
        acc = models.UserAccounts.objects.filter(user = request.user.id)
            

        return render(request , 'user/profile.html' , {'sub' : sub , 'day' : day , 'form' : form , 'account_form' : account_form , 'useracc' :acc})
    


    def post(self, request) : 
        form = forms.get_gift(request.POST )
        if form.is_valid() : 
        
            cd = form.cleaned_data
            check= md.Gift.objects.filter(code = cd['code'])
            if len(check) != 0 : 
                gift= md.Gift.objects.get(code = cd['code'])
                giftuser = models.GiftUser.objects.filter(user = request.user ,gift = gift).exists()
                user = User.objects.get(id = request.user.id)
                if gift.used <= gift.count : 
                    if giftuser == False  : 
                        days = user.userdata.subscription-datetime.datetime.now().date()
                        if days.days < 0 : 
                            new = datetime.datetime.now().date() + datetime.timedelta(days=gift.day)
                            user.userdata.subscription = new
                            user.userdata.account_count += gift.count
                            user.userdata.save()
                            gift.used += 1
                            gift.save()
                            messages.success(request  , 'کد هدیه با موفقیت اعمال شد' , 'success')
                        else:
                            new = user.userdata.subscription + datetime.timedelta(days=gift.day)
                            user.userdata.subscription = new
                            user.userdata.account_count += gift.count
                            user.userdata.save()
                            gift.used += 1
                            gift.save()
                            messages.success(request  , 'کد هدیه با موفقیت اعمال شد' , 'success')
                        models.GiftUser.objects.create(user = request.user , gift = gift)

                    else : 
                        messages.success(request  , 'کد وارد شده تکراری است .' , 'warning')
                else :
                    messages.success(request  , 'کد وارد شده منقضی شده است .' , 'warning')
            else :
                messages.success(request  , 'کد وارد شده اشتباه است .' , 'warning')
                return redirect('user:profile')
            return redirect('user:profile')
        messages.success(request  , 'کد وارد شده اشتباه است .' , 'warning')
        return redirect('user:profile')
        
        



class UserAccountsView(LoginRequiredMixin , View) : 
    def post(self, request) : 
        form = forms.add_fpass(request.POST)
        if form.is_valid() : 
            cd = form.cleaned_data
            second= cd['second']
            if second <180  : 
                second = 180

            print(second)
            if cd['fpass'].isascii():
                
                NameOP= {'User-Agent' : "Dalvik/2.1.0 (Linux; U; Android 13; SM-A326B Build/TP1A.220624.014)" ,'Connection':'close','Content-Type':"application/x-www-form-urlencoded" ,'Cookie':"FRUITPASSPORT="f"{cd['fpass']}"}
                data = requests.get('http://iran.fruitcraft.ir/cards/collectgold' , headers = NameOP)
                content = data.content
                print(content)
                if len(content) < 500 : 
                    x = json.loads(data.content)
                    redata = x['data']
                    check = models.UserAccounts.objects.filter(fpass = cd['fpass']).exists()
            
                    if check == False : 
                            if request.user.userdata.account_used < request.user.userdata.account_count :
                                servers =  md.Server.objects.all()
                                if len(servers) > 0 :
                                    for i in servers : 
                                        res = requests.get(i.link)
                                        if res.status_code  == 200 :
                                            w1  ,w2 = json.loads(res.content)['worker1']['status'] , json.loads(res.content)['worker2']['status']
                                            if w1 == 'off' or w2 == 'off' : 

                                                fpass = cd['fpass']
                                                userid = request.user.id
                                                day = request.user.userdata.subscription-datetime.datetime.now().date()
                                                send = requests.get(f'{i.link}/sender/{fpass}/{day.days}/{userid}/{str(second)}')
                                                
                                                if send.status_code == 200 : 
                                                    jsend = json.loads(send.content)
                                                    if jsend['status'] != 'duplicate' : 

user/templates/user/login.html
{% extends 'base.html' %}



{% block title %}
log in user
{% endblock %}



{% block main %}
<main>


    
</main>
<div class="text-center form-floating">
    <h1 class="h3 mb-3 fw-normal">ورود به حساب کاربری</h1>
    <form action="" method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class=" w-30 btn btn-lg btn-primary" value="ورود">
    </form>
    
</div>

{% endblock %}




<!-- <link href="signin.css" rel="stylesheet">
</head>
<body class="text-center">
  
<main class="form-signin w-100 m-auto">
<form>
  <img class="mb-4" src="/docs/5.2/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
  <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

  <div class="form-floating">
    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
    <label for="floatingInput">Email address</label>
  </div>
  <div class="form-floating">
    <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
    <label for="floatingPassword">Password</label>
  </div>

  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017–2022</p>
</form>
</main>


  
</body>
</html> -->

user/templates/user/profile.html
{% extends 'base.html' %}



{% block title %}
log in user
{% endblock %}



{% block main %}

<div class="card text-center m-4 mt-5">
    <div class="card-header">
      اطلاعات حساب
    </div>
    <div class="card-body" >
      <h5 class="card-title">تاریخ اشتراک : 
        {% if sub == False %}
        ندارید
        {% else %}
        {{day}} روز
        {{date}}
      {% endif %}
      </h5>
      <h5 class="card-title">اکانت های مجاز   : {{request.user.userdata.account_count}} </h5>
      <h5 class="card-title">اکانت های ثبت شده  : {{request.user.userdata.account_used}} </h5>
      
    </div>
    <div id="accordion">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-primary" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              افزودن کد هدیه
            </button>
          </h5>
        </div>
    
        <div id="collapseOne" class="collapse hide" aria-labelledby="headingOne" data-parent="#accordion">
          <div class="card-body">
            <form class="form-inline"  method="post" action="{% url 'user:profile'%}">
              <div class="form-group mb-2">
              </div>
              <div class="form-group mx-sm-3 mb-2">
                {{form.as_p}}
                {%csrf_token%}
              </div>
              <button type="submit" class="btn btn-primary mb-2">تایید</button>
            </form>          </div>
        </div>
      </div>

  </div>










  <!-- #________________________________________________________________________________ -->

  <div class="card text-center m-4 mt-5">
    <div class="card-header">
      اکانت های من
    </div>
    <div class="card-body">



    </div>
    <div id="accordion">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-success" data-toggle="collapse" data-target="#collapseadd" aria-expanded="true" aria-controls="collapseOne">
 + افزودن اکانت +
            </button>
          </h5>
        </div>
    
        <div id="collapseadd" class="collapse hide" aria-labelledby="headingOne" data-parent="#accordion">
          <div class="card-body">
            <form class="form-inline"  method="post" action="{% url 'manager:acc' %}">
              <div class="form-group mb-2">
              </div>
              <div class="form-group mx-sm-3 mb-2">
                {{account_form.as_p}}
                {%csrf_token%}
              </div>
              <button type="submit" class="btn btn-primary mb-2">تایید</button>
            </form>          </div>
        </div>
      </div>
      


      {% for i in useracc %}
      
      <div id="accordion">
        <div class="card">
          <div class="card-header" id="headingOne">
            <h5 class="mb-0">
              <button class="btn btn-link" data-toggle="collapse" data-target="#collapseAccount" aria-expanded="true" aria-controls="collapseOne">
                {{ i.fpass }}
              </button>
            </h5>
          </div>
      
          <div id="collapseAccount" class="collapse hide" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
              <p>
                second = {{i.second}}
                <br>
              collected_gold =  {{i.collected_gold}}
              <br>

              player_gold =  {{i.player_gold}}
              <br>

              gold_collection_allowed =  {{i.gold_collection_allowed}}
              <br>

              gold_collection_allowed_at =  {{i.gold_collection_allowed_at}}
              <br>

              gold_collection_extraction =  {{i.gold_collection_extraction}}
              <br>

              last_gold_collect_at =  {{i.last_gold_collect_at}}
              <br>

              needs_captcha =  {{i.needs_captcha}}
              <br>

              </p>
              
              <a href="{% url 'user:kill' i.fpass%}" class="btn btn-danger">خاموش</a>
              
          
            </div>
          </div>
        </div>
           </div>

  </div>
  {% endfor %}


{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}



{% block title %}
log in user
{% endblock %}



{% block main %}


<div class="text-center">


    <h1 class="h3 mb-3 fw-normal">ثبت نام</h1>
    <form action="" method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class=" w-30 btn btn-lg btn-primary" value="تایید">
    </form>
</div>
{% endblock %}