main/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('user.urls' , namespace='user')) , 
    path('manager/' , include('manager.urls' , namespace='manager'))
]

user/urls.py
from django.urls import path
from . import views


app_name = 'user'

urlpatterns = [
    path('register/' , views.UserRegister.as_view() , name='register') , 
    path('login/' , views.UserLogin.as_view() , name='login') , 
    path('logout/' , views.UserLogOut.as_view() , name = 'logout') , 
    path('' , views.UserProfile.as_view() , name='profile') , 
    path('kill/<str:fpass>' , views.KillFpass.as_view() , name='kill')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>
        
        {% block title %} {% endblock %}
    </title>
</head>
<body>


<div class="text-center">
    {% include 'nav.html' %} 
    {% include 'messages.html' %} 

</div>

    {% block main %} 

    
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script> 
</body>
</html>

templates/messages.html
{% if messages %}
{% for i in messages %}

<p class="alert alert-{{i.tags}}">{{i}}</p>
{% endfor %}



{% endif %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  {% if request.user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'user:profile' %}">سلام [ {{request.user}} ]</a>
    
    {% endif %}

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        {% if request.user.is_authenticated %}
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:logout' %}">خروج </a>
          </li>
        {% else %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:login' %}">ورود </a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:register' %}">ثبت نام </a>
          </li>
          



{% endif %}
      </ul>
      
    </div>
  </nav>